"""
Confluence REST API client for auto-publishing sprint backlogs.
Supports Confluence Cloud (Atlassian REST API v2).
"""
import os
import re
import json
from typing import Optional


def _make_adf_doc(content_blocks: list) -> dict:
    """Wrap blocks in Atlassian Document Format (ADF) root."""
    return {"version": 1, "type": "doc", "content": content_blocks}


def _heading(text: str, level: int = 2) -> dict:
    return {"type": "heading", "attrs": {"level": level}, "content": [{"type": "text", "text": text}]}


def _paragraph(text: str, bold: bool = False) -> dict:
    marks = [{"type": "strong"}] if bold else []
    return {"type": "paragraph", "content": [{"type": "text", "text": text, "marks": marks}]}


def _bullet_list(items: list[str]) -> dict:
    return {
        "type": "bulletList",
        "content": [
            {"type": "listItem", "content": [_paragraph(item)]}
            for item in items
        ]
    }


def _table(headers: list[str], rows: list[list[str]]) -> dict:
    def cell(text: str, is_header: bool = False) -> dict:
        cell_type = "tableHeader" if is_header else "tableCell"
        return {"type": cell_type, "content": [_paragraph(text)]}

    header_row = {"type": "tableRow", "content": [cell(h, True) for h in headers]}
    data_rows = [
        {"type": "tableRow", "content": [cell(str(v)) for v in row]}
        for row in rows
    ]
    return {"type": "table", "content": [header_row] + data_rows}


def _rule() -> dict:
    return {"type": "rule"}


class ConfluenceClient:
    def __init__(self, base_url: str, email: str, api_token: str, space_key: str = ""):
        self.base_url = base_url.rstrip("/")
        self.email = email
        self.api_token = api_token
        self.space_key = space_key

    def _headers(self) -> dict:
        import base64
        auth = base64.b64encode(f"{self.email}:{self.api_token}".encode()).decode()
        return {
            "Authorization": f"Basic {auth}",
            "Content-Type": "application/json",
            "Accept": "application/json"
        }

    def _api(self, path: str) -> str:
        return f"{self.base_url}/wiki/rest/api{path}"

    def get_spaces(self) -> list:
        """List available spaces."""
        try:
            import httpx
            r = httpx.get(self._api("/space"), headers=self._headers(), timeout=15.0)
            r.raise_for_status()
            return r.json().get("results", [])
        except Exception as e:
            raise RuntimeError(f"Confluence API error: {e}")

    def publish_sprint_backlog(
        self,
        session_data: dict,
        space_key: str,
        parent_page_id: Optional[str] = None
    ) -> dict:
        """
        Create or update a Confluence page with the full sprint backlog.
        Returns the created/updated page URL.
        """
        import httpx

        epics = session_data.get("epics", [])
        stories = session_data.get("stories", [])
        telemetry = session_data.get("telemetry", {})
        title = session_data.get("title", "AI-Generated Sprint Backlog")
        prd_filename = session_data.get("prd_filename", "")

        # Build ADF content
        blocks = [
            _heading(f"🤖 {title}", level=1),
            _paragraph(f"Auto-generated by Agiler AI from: {prd_filename or 'PRD document'}", bold=False),
            _rule(),
        ]

        # Summary stats
        total_sp = sum(int(s.get("storyPoints", 0)) for s in stories)
        blocks += [
            _heading("📊 Sprint Summary", level=2),
            _table(
                headers=["Metric", "Value"],
                rows=[
                    ["Total Epics", str(len(epics))],
                    ["Total Stories", str(len(stories))],
                    ["Total Story Points", str(total_sp)],
                    ["AI Generation Cost", f"${round(telemetry.get('totalCostUSD', 0), 4)}"],
                    ["Models Used", telemetry.get("model", "GPT-4o")],
                ]
            ),
            _rule(),
        ]

        # Epics + their stories
        blocks.append(_heading("📋 Epics & User Stories", level=2))
        for epic in epics:
            epic_id = epic.get("id") or epic.get("name", "")
            epic_stories = [s for s in stories if s.get("epicId") == epic_id or s.get("epic") == epic.get("name")]
            blocks.append(_heading(f"Epic: {epic.get('name', 'Unknown')}", level=3))
            blocks.append(_paragraph(epic.get("description", "")))

            if epic_stories:
                story_rows = [
                    [
                        s.get("title", ""),
                        str(s.get("storyPoints", "?")),
                        s.get("type", "Feature"),
                        s.get("priority", "Medium"),
                        s.get("assignee", "Unassigned"),
                    ]
                    for s in epic_stories
                ]
                blocks.append(_table(
                    headers=["Story", "Points", "Type", "Priority", "Assignee"],
                    rows=story_rows
                ))

        # Acceptance criteria section
        blocks += [_rule(), _heading("✅ Acceptance Criteria Summary", level=2)]
        for story in stories[:10]:  # Cap at 10 for readability
            blocks.append(_paragraph(story.get("title", ""), bold=True))
            criteria = story.get("acceptanceCriteria", [])
            if criteria:
                blocks.append(_bullet_list([str(c) for c in criteria[:5]]))

        adf_body = _make_adf_doc(blocks)

        payload = {
            "type": "page",
            "title": f"[AI] {title}",
            "space": {"key": space_key},
            "body": {"storage": {"value": json.dumps(adf_body), "representation": "atlas_doc_format"}},
        }
        if parent_page_id:
            payload["ancestors"] = [{"id": parent_page_id}]

        # Check if page already exists
        client = httpx.Client(timeout=30.0)
        search_r = client.get(
            self._api(f"/page?spaceKey={space_key}&title=[AI]+{title.replace(' ', '+')}"),
            headers=self._headers()
        )
        existing = search_r.json().get("results", []) if search_r.status_code == 200 else []

        if existing:
            # Update existing page
            page_id = existing[0]["id"]
            current_version = existing[0]["version"]["number"]
            payload["version"] = {"number": current_version + 1}
            r = client.put(self._api(f"/content/{page_id}"), headers=self._headers(), json=payload, timeout=30.0)
        else:
            # Create new page
            r = client.post(self._api("/content"), headers=self._headers(), json=payload, timeout=30.0)

        client.close()
        if r.status_code not in (200, 201):
            raise RuntimeError(f"Confluence publish failed ({r.status_code}): {r.text[:300]}")

        page_data = r.json()
        page_url = f"{self.base_url}/wiki{page_data.get('_links', {}).get('webui', '')}"
        return {"pageId": page_data.get("id"), "url": page_url, "title": payload["title"]}
